name: Warm Vercel App

on:
  schedule:
    - cron: "*/10 * * * *" # roda a cada 10 minutos (em UTC)
  workflow_dispatch: {} # permite executar manualmente pelo GitHub

concurrency:
  group: warm-vercel
  cancel-in-progress: true

jobs:
  warm:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Pingar /api/warm
        env:
          WARM_URL: ${{ secrets.WARM_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$WARM_URL" ]; then
            echo "❌ WARM_URL não definido. Defina o secret WARM_URL no repositório."
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "❌ CRON_SECRET não definido. Defina o secret CRON_SECRET no repositório."
            exit 1
          fi

          echo "🔁 Pinging $WARM_URL"
          RESPONSE=$(curl -sS --max-time 20 -H "Authorization: Bearer $CRON_SECRET" "$WARM_URL" || true)
          echo "Resposta do endpoint:"
          echo "$RESPONSE"
          echo "::notice::Verificação concluída."
          exit 0
